apiVersion: v1
data:
  mapRoles: "- rolearn: arn:aws:iam::713432144879:role/eks-worker-nodes-NodeInstanceRole-6K52QWPHAH1D\n
    \ username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n
    \   - system:nodes \n- rolearn: arn:aws:iam::713432144879:role/EKSCustomAMIWorker-NodeInstanceRole-1WTKBNJXYYNY2\n
    \ username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n
    \   - system:nodes \n- rolearn: arn:aws:iam::713432144879:role/ToolBox-RootInstanceRole-GJBMDN3S660J\n
    \ username: admin\n  groups:\n    - system:masters\n
    - rolearn: arn:aws:iam::713432144879:role/service-role/codebuild-case-service-role\n
    \ username: build\n  groups:\n    - system:masters\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::713432144879:role/eks-worker-nodes-NodeInstanceRole-6K52QWPHAH1D\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: 2019-03-30T10:35:35Z
  name: aws-auth
  namespace: kube-system
  resourceVersion: "16589868"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8d7f6c06-52d7-11e9-947a-0a3d0ce2a466
