apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplenodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simplenodejs
  template:
    metadata:
      labels:
        app: simplenodejs
    spec:
      containers:
      - name: simplenodejs
        image: 713432144879.dkr.ecr.ap-southeast-2.amazonaws.com/simplenodejs:1
        ports:
        - containerPort: 8080
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
