kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: my-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: gp2
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 8Gi
