apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: simplenodejs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
         - simplenodejs
  template:
    metadata:
      labels:
        app: simplenodejs
    spec:
      containers:
      - name: simplenodejs
        image: 713432144879.dkr.ecr.ap-southeast-2.amazonaws.com/simplenodejs
